import type { Metadata } from "next";
import "./globals.css";
import ContextProvider from "./context/Context";
import { Toaster } from "react-hot-toast";
import TopHeader from "./components/TopHeader";
import BtmHeader from "./components/BtmHeader";
import Footer from "./components/Footer";
import Scroll from "./components/Scroll";

export const metadata: Metadata = {
  title: "Amazon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/icon-amazon.png" />
        <title>Amazon</title>
      </head>
      <body>
        <ContextProvider>
          <Scroll />
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#fff",
                padding: "15px",
                borderRadius: "20px",
              },
            }}
          />
          <header>
            <TopHeader />
            <BtmHeader />
          </header>

          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
